Edit Rules submenu
Submenu option to edit all (except downloaded.rules) enabled rule files, also providing pre-edit backups and retention pruning.

diff --git a/so_utils b/so_utils
--- a/so_utils
+++ b/so_utils
@@ -346,34 +346,62 @@ function su_editDisSID {
 
 
 ######################################################################
-# Modify Snort local.rules
+# Edit Rules
 #
-# Opens local.rules in a text editor, and creates a backup
-# BEFORE you make any changes into the /var/backups/rules
-# directory.
+# Lists rules enabled via snort.conf for editing. Provides backup
+# and pruning features as well. Backups are stored in the following
+# location: /var/backups/rules.
 ######################################################################
-function su_editlocalRules {
-	backup=$rul_bk/local.rules.`date +%m%d%Y_%H%M%S`
+function su_ruleMenu {
+	RULE_PATH=`cat /etc/nsm/templates/snort/snort.conf | grep "^var RULE_PATH" | cut -f3 -d' '`
+	rules=`cat /etc/nsm/templates/snort/snort.conf | grep "^include .*\.rules" | grep -v "downloaded\.rules" | cut -f2 -d' '`
+	rules="${rules//\$RULE_PATH/$RULE_PATH}"
+	total=`echo "$rules" | wc -l`
 
-	if ! [[ -d $rul_bk ]]; then mkdir $rul_bk; fi
+	while [[ 2 -gt 1 ]]; do
+		clear
+		count=1
 
-	cp /etc/nsm/rules/local.rules $backup
-	printf "Backup created at $backup\n"
-	$su_editor /etc/nsm/rules/local.rules 2>/dev/null
+		printf "Security Onion Utilities (ver. $su_version) >> Edit Rules\n\nThe following are your currently enabled rule files as configured in snort.conf.\n\n"
 
-	count=`find $rul_bk -name "local.rules.*" -mtime +$retention | wc -l`
-	if [[ $count -gt 0 ]]; then
-		echo "You currently have $count backups older than $retention days."
-		echo -n "Prune? [y/N]: "; read junk
+		while [[ $count -le $total ]]; do
+			echo "[$count] `echo \"$rules\" | head -$count | tail -1 | rev | cut -f1 -d'/' | rev`"
+			count=$((count+1))
+		done
+		echo "[Q] Return to main menu"; echo ""
+		echo -n "Option: "; read junk
 
-		if [[ "$junk" == [yY] ]]; then
-			find $rul_bk -name "local.rules.*" -mtime +$retention -exec rm -f {} \;
+		if [[ "$junk" == [0qQ] ]]; then
+			break
+
+		elif ! [[ "$junk" =~ ^[0-9]+$ ]] || [[ "$junk" -gt "$total" ]]; then
+			echo "Invalid option!"
 			echo "--- Press [Enter] to continue ---"; read -s
-		fi
-	fi
 
-	echo "Make sure to run rule update to commit your changes!"
-	echo "--- Press [Enter] to continue ---"; read -s
+		elif [[ "$junk" -le "$total" ]]; then
+
+			filePath=`echo "$rules" | head -$junk | tail -1`
+			file=`echo "$filePath" | rev | cut -f1 -d'/' | rev`
+			backup=$rul_bk/$file.`date +%m%d%Y_%H%M%S`
+
+			if ! [[ -d $rul_bk ]]; then mkdir $rul_bk; fi
+
+			cp $filePath $backup
+			printf "Backup created at $backup\n"
+			$su_editor `echo "$rules" | head -$junk | tail -1`
+
+			count=`find $rul_bk -name "$file.*" -mtime +$retention | wc -l`
+			if [[ $count -gt 0 ]]; then
+				echo "You currently have $count backups older than $retention days."
+				echo -n "Prune? [y/N]: "; read junk
+
+				if [[ "$junk" == [yY] ]]; then
+					find $rul_bk -name "$rule.*" -mtime +$retention -exec rm -f {} \;
+					echo "--- Press [Enter] to continue ---"; read -s
+				fi
+			fi
+		fi
+	done
 }
 
 
@@ -625,7 +653,7 @@ printf "Security Onion Utilities (ver. $su_version)
  [${bu}8${nrml}] ${bu}e${nrml}nablesid.conf 			[${bu}19${nrml}] Disable User
  [${bu}9${nrml}] ${bu}m${nrml}odifysid.conf 			
 [${bu}10${nrml}] ${bu}d${nrml}isablesid.conf 			=== Misc
-[${bu}11${nrml}] ${bu}l${nrml}ocal.rules 			[${bu}20${nrml}] Create Desktop Shortcut
+[${bu}11${nrml}] Edit Rules			[${bu}20${nrml}] Create Desktop Shortcut
 					 [${bu}0${nrml}] Quit\n\n"
 
 		echo -n "Option: "; read junk
@@ -670,9 +698,9 @@ printf "Security Onion Utilities (ver. $su_version)
 			clear
 			su_editDisSID
 
-		elif [[ "$junk" == 11 || "$junk" == [lL] ]]; then
+		elif [[ "$junk" == 11 ]]; then
 			clear
-			su_editlocalRules
+			su_ruleMenu
 
 		elif [[ "$junk" == 12 ]]; then
 			clear
